### ISSUE TITLE
При открытых комментариях, плавающий блок наезжает на контент

### ISSUE THREAD

**Issue by 6y6b07** [razrabs-media/journal#133]

**Comment by 6y6b07** [comment]
![Image](https://user-images.githubusercontent.com/101573341/177766317-94828905-5fb7-4bb5-b9de-92d932603b11.png)

**Comment by 6y6b07** [comment]
![Image](https://user-images.githubusercontent.com/101573341/177781140-810aee5d-3ccd-4a0b-b125-ef04beb44385.png)

**Comment by raantoniv** [comment]
неактуально
