### ISSUE TITLE
На главной странице, между карточками статей и футером отступ не соответствует макету (https://github.com/razrabs-media/journal/pull/136)

### ISSUE THREAD

**Issue by 6y6b07** [razrabs-media/journal#137]

**Comment by 6y6b07** [comment]
![Image](https://user-images.githubusercontent.com/101573341/178977425-e9a7153a-6bba-4bcb-bed0-bd6093ef4228.png)

**Comment by raantoniv** [comment]
Актуально для ветки https://github.com/razrabs-media/journal/pull/136
