### ISSUE TITLE
Общее положение элементов в статье при открытых комментах не соответствует макету

### ISSUE THREAD

**Issue by 6y6b07** [razrabs-media/journal#172]
Комменты должны сдвигать на ширину превью, а превью исчезать 

https://www.figma.com/proto/NO0RmwhfZnsOjW1cexIVEW/%F0%9F%94%B8-rzrbs?page-id=60%3A2&node-id=3307%3A3704&viewport=-7152%2C-6218%2C0.28&scaling=scale-down&starting-point-node-id=3307%3A3704

**Comment by batyshkaLenin** [comment]
@6y6b07 проблема актуальна?

**Comment by batyshkaLenin** [comment]
@6y6b07 проблема актуальна?

**Comment by 6y6b07** [comment]
Нет)
