### ISSUE TITLE
Design: Заголовки и подзаголовки стать (h1-h6)

### ISSUE THREAD

**Issue by raantoniv** [razrabs-media/journal#186]

**Comment by batyshkaLenin** [comment]
Можно поподробнее, о чём идёт речь?

**Comment by batyshkaLenin** [comment]
![изображение](https://user-images.githubusercontent.com/8469236/184922233-a2d45888-77d4-4fda-a4fd-d24bd2c5e7c4.png)
На главной и странице фидов нет заголовков.

**Comment by raantoniv** [comment]
Дубликат https://github.com/razrabs-media/journal/issues/468
