### ISSUE TITLE
В мобильной версии на главной странице, увеличить отступы между картинками и заголовками. ( карточки занимающие 1 -2 клетки)

### ISSUE THREAD

**Issue by 6y6b07** [razrabs-media/journal#226]
![Image](https://user-images.githubusercontent.com/101573341/180492354-0ce6f3e9-1947-4ad7-8b1b-c2da50ea051e.png)

**Comment by raantoniv** [comment]
Исходя из макета отступ следует, наоборот, уменьшить до 10px
