### ISSUE TITLE
При разрешение экрана менее 1148, панель комментариев перекрывает часть контента ( в постах с блоками кода)

### ISSUE THREAD

**Issue by 6y6b07** [razrabs-media/journal#262]
![Image](https://user-images.githubusercontent.com/101573341/181633746-0cbc5559-b802-45dd-88b3-3105d14602f7.png)

**Comment by gkopylovdev** [comment]
Актуальна ли проблема? Если да, то хочется узнать версию хрома. На маке в хроме все ок 
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/28918530/183299050-5c34e098-64b4-4537-941a-513deb9678c6.png">

**Comment by 6y6b07** [comment]
Уже не актуально)
