### ISSUE TITLE
После авторизации редиректить на ту же страницу, с которой авторизовывался, а не наглавную

### ISSUE THREAD

**Issue by Suvitruf** [razrabs-media/journal#281]

**Comment by devmartynov** [comment]
а почему должен быть редирект на главную?
это ux паттерн како-то? вроде даже логично, что остаешься на той же странице

**Comment by Suvitruf** [comment]
> а почему должен быть редирект на главную?
> это ux паттерн како-то? вроде даже логично, что остаешься на той же странице

Так я и прошу, чтоб на той же странице оставляло 🤔

**Comment by devmartynov** [comment]
@Suvitruf извини, это у меня галаза запотели, банально прочитал неправильно.

**Comment by axaxaman** [comment]
кажется дублирует https://github.com/razrabs-media/journal/issues/139
