### ISSUE TITLE
В шапке, время изменяется только после обновления страницы [re-open]

### ISSUE THREAD

**Issue by a-kovrigin** [razrabs-media/journal#294]
#198 актуален, время обновляется только после перезагрузки страницы.

**Comment by batyshkaLenin** [comment]
@evist0 а что означает это время, в чем его функциональность?

**Comment by raantoniv** [comment]
Это время получения страницы. Оно не должно обновляться иным образом

**Comment by zhookovhz** [comment]
> Это время получения страницы. Оно не должно обновляться иным образом

А какая в этом функциональная польза?
