### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by ninedev-i** [razrabs-media/journal#310]
Нужен адекватный ридми для локального запуска.
Не помешала бы ссылка на макеты (в фигме?), чтобы желающие поконтрибьютить могли править баги несоответствия макетам.

**Comment by anyxem** [comment]
А был ли макет...

**Comment by philippranzhin** [comment]
Ссылка на макеты скоро будет, ридми тоже сделаем

**Comment by philippranzhin** [comment]
Ссылка на макеты тут #319 

hblvb j,yjdbkb
