### ISSUE TITLE
Minified 418, 423, 425  errors

### ISSUE THREAD

**Issue by Skrebnevf** [razrabs-media/journal#315]
-MacOS 10.15.7
-Chrome current
--Открыть главную
--или
--Залогинется
В консоль падают ошибочки 
Отлавливается при помощи минифицированной версии Реакт. Каждую ошибку по отдельности можно будет отловить и пофиксить
<img width="1027" alt="Снимок экрана 2022-08-03 в 08 42 10" src="https://user-images.githubusercontent.com/40490810/182543319-fc5e782d-0397-400a-9293-a253f409c9e2.png">

**Comment by evist0** [comment]
да, проблема в основном с отображением времени на гидратации, скоро пофиксим

**Comment by evist0** [comment]
Duplicates #256
