### ISSUE TITLE
Разработка фич

### ISSUE THREAD

**Issue by philippranzhin** [razrabs-media/journal#319]
Если вы хотите сами как-то менять фронт медиа, вам стоит делать это в соответствии с макетами, они лежат [здесь](https://www.figma.com/file/NO0RmwhfZnsOjW1cexIVEW/%F0%9F%94%B8-rzrbs?node-id=60%3A2)

Обсуждать их и спрашивать, что из макетов - финальный вариант а что ещё в работе можно так же спрашивать под этим ишью, наши дизайнеры будут его мониторить

**Comment by raantoniv** [comment]
см. https://github.com/razrabs-media/journal/blob/main/CONTRIBUTING.md
