### ISSUE TITLE
URL линки на разделы статьи

### ISSUE THREAD

**Issue by n1k1ta42** [razrabs-media/journal#326]
Хотелось бы видеть урл линки на разделы, что бы можно было делиться именно разделом лонгрида

**Comment by batyshkaLenin** [comment]
В #322, насколько я понимаю, описано то же самое, я правильно понимаю?

**Comment by n1k1ta42** [comment]
Все так сори, закрою ишью

**Comment by batyshkaLenin** [comment]
@n1k1ta42 всё в порядке, будут ещё предложения пиши!
