### ISSUE TITLE
Добавить в статье поле "время чтения"

### ISSUE THREAD

**Issue by proggga** [razrabs-media/journal#339]
В наше время ты пытаешься сэкономить или оптимизировать время. И когда у тебя есть 5-10-15 минут хочешь прочитать статью но видишь большую статью и Не читаешь тк хз сколько она займёт. В медиуме есть время чтения (думаю взяли среднюю скорость чтения в мире и разделили количество символов) было б круто увидеть это поле рядом с датой публикации ![image](https://user-images.githubusercontent.com/12262156/182917005-260acc9a-e34d-4630-8d38-ede648669bd1.png)![image](https://user-images.githubusercontent.com/12262156/182917018-99901747-8ce7-472a-8c91-8d28199e7fb3.jpeg)

Пример статьи на [медиуме](https://medium.com/там-где-мы-есть/переезд-в-нидерланды-шпаргалка-на-все-случаи-жизни-22f12ce6a13c)

**Comment by philippranzhin** [comment]
Принципиальная позиция редакции — ни при каких обстоятельствах этого не делать по причине: "отвратительная утилитарность"

**Comment by proggga** [comment]
Обида!
