### ISSUE TITLE
Проблемы с вёрсткой футера на мобильных устройствах

### ISSUE THREAD

**Issue by proggga** [razrabs-media/journal#340]
Футер говорит "связаться" но вместо формы или напр ишьюс на гх ведёт на Твиттер (Личка закрыта), в ютюб (писать комменты??) и в тг (ридонли канал?)

Го либо ссылку на issue/ readme.md где написано что делать либо переименовать в "соцсети"

Кмк нужно и то и другое

**Comment by batyshkaLenin** [comment]
Ссылка ведёт на почту, там используется формат mailto:mail@mail.com. Как правило, в любой ОС это открывает почтовый клиент где проставлен адрес указанный в такой ссылке. С этим есть какие-то проблемы?

**Comment by proggga** [comment]
Я не так понял гуй

Я был уверен 
О нас: гитхаб

Связаться: тг ютюб Твиттер ![image](https://user-images.githubusercontent.com/12262156/182937336-9d6d7fff-4c16-4f5a-af8c-fe61bc180633.jpeg)

**Comment by batyshkaLenin** [comment]
@proggga я глянул в макет, так и задумано, возможно, конечно, это надо менять, но всё же
