### ISSUE TITLE
Время прошедшее после регистрации

### ISSUE THREAD

**Issue by rchaser** [razrabs-media/journal#346]
![image](https://user-images.githubusercontent.com/1940857/182950289-d1a2051a-0ef7-4f26-93b1-7b956b343736.png)
Я зарегался 5 минут назад, у меня 3 часа дня, откуда взялось "8 часов"? я понимаю это проблема только для первого дня
Может округлять до дней? пусть будет "0 дней" вполне по айтишному

**Comment by batyshkaLenin** [comment]
@evist0 #284 опять повторилась

**Comment by evist0** [comment]
так не влили же ещё релиз или чё?

https://github.com/razrabs-media/journal/actions/workflows/release-deployment.yml

**Comment by raantoniv** [comment]
> > @evist0 #284 опять повторилась
> 
> так не влили же ещё релиз или чё?
> 
> https://github.com/razrabs-media/journal/actions/workflows/release-deployment.yml

все верно, новый патч пока не развернут, ориентировочная дата развертывания 6.08

**Comment by batyshkaLenin** [comment]
Понял, я думал уже в релизе
