### ISSUE TITLE
Добавить опциональное отображение статей по порядку

### ISSUE THREAD

**Issue by CommanderTvis** [razrabs-media/journal#361]
**Что это решает и поможет?**
Добавить в личные настройки пользователи флажок "Показывать материалы по порядку". Некоторым, например мне, так удобнее.

**Описание желаемого результата**
Если этот флажок выбран, то статьи (кроме, возможно, отмеченных редакцией как главные) отобрааются на галереей, а как лента по времени публикации.

**Референсы и альтернативы**

Референс - "Медуза".

Вот так она выглядит по умолчанию:
![image](https://user-images.githubusercontent.com/38042667/183284238-4409cc13-87a2-4340-acaa-e8f84bcefca1.png)
А так, если нажать на кнопку "Показывать по порядку":
![image](https://user-images.githubusercontent.com/38042667/183284264-f42dd8a5-7b8b-437f-9376-3663e6602448.png)

**Comment by philippranzhin** [comment]
Этот функционал реализован через ленту "Всё подряд", главная всегда будет выглядеть так, как хочет главный редактор — идеологическое решение

**Comment by CommanderTvis** [comment]
> Этот функционал реализован через ленту "Всё подряд", главная всегда будет выглядеть так, как хочет главный редактор — идеологическое решение

А, найс, я просто не заметил ее
