### ISSUE TITLE
На мобильных устройствах на проде при разрешение 375 на главной странице, карточки постов не адаптируются под размер экрана, пропал отступ справа.

### ISSUE THREAD

**Issue by 6y6b07** [razrabs-media/journal#372]
![Image](https://user-images.githubusercontent.com/101573341/183456292-7154a8b8-acb7-4d66-8011-0b9cae55f630.png)

**Comment by batyshkaLenin** [comment]
В актуальной версии которую ещё не зарелизили не подтвердилось
![Скриншот сделанный 2022-08-08 в 23 08 11](https://user-images.githubusercontent.com/8469236/183463068-a0d663c1-5074-4d2d-ac4b-9c4befe49f17.png)
