### ISSUE TITLE
Доработка светлой темы на дев контуре

### ISSUE THREAD

**Issue by default-razrab** [razrabs-media/journal#384]
https://dev.razrabs.ru/

сейчас
![photo_2022-08-10 00 48 53](https://user-images.githubusercontent.com/101455229/183767911-a05983a5-e63b-42b3-85a4-937b932cc7da.jpeg)
надо 
https://www.figma.com/file/NO0RmwhfZnsOjW1cexIVEW/%F0%9F%94%B8-rzrbs?node-id=4370%3A9759

сейчас
![photo_2022-08-10 00 48 57](https://user-images.githubusercontent.com/101455229/183767918-1da41aa3-3680-467a-8858-877dd471ad05.jpeg)
надо
![photo_2022-08-10 00 49 00](https://user-images.githubusercontent.com/101455229/183767923-db6098c1-cc39-4721-b025-c23abfc2af75.jpeg)

**Comment by batyshkaLenin** [comment]
@default-razrab а почему критикал?

**Comment by philippranzhin** [comment]
потому что хотим в ближайший релиз

**Comment by batyshkaLenin** [comment]
Так суть критикала в том, что без исправления этим НЕВОЗМОЖНО пользоваться в принципе, разве нет? Это может быть high, потому что очень важно, а не критикал или я чего-то не понимаю?

**Comment by gkopylovdev** [comment]
@batyshkaLenin Бахни на меня, вечерком сделаю

**Comment by gkopylovdev** [comment]
Пофиксил бОльшую часть, критов вроде не осталось. Есть моменты, где были сделаны костыли, ради дизайна и которые смущают:
1) В темной теме в цвете текста в инпуте комментов используется текст из светлой темы ([дизайн](https://www.figma.com/file/NO0RmwhfZnsOjW1cexIVEW/%F0%9F%94%B8-rzrbs?node-id=3839%3A7843)). Ок ли нам использовать инвертированные цвета? (первый скрин)
2) При выделении текста на темной теме цвет текста становится contrastPrimary, а на светлой просто primary
3) Бекграунд блока комментариев и всего сайта разные, а на светлой теме одинаковые
4) Блоки кода в статье в целом отличаются от дизайна, т.к. юзается внешняя либа [со встроенными стилями](https://react-syntax-highlighter.github.io/react-syntax-highlighter/demo/prism.html). Возможно стоить натянуть дизайны на эту либу, либо костылить собственные стили


<img width="680" alt="image" src="https://user-images.githubusercontent.com/28918530/183892369-4054c02d-cbf4-4b89-84dd-76b1d9e7306b.png">

**Comment by default-razrab** [comment]
> @philippranzhin Так суть критикала в том, что без исправления этим НЕВОЗМОЖНО пользоваться в принципе, разве нет? Это может быть high, потому что очень важно, а не критикал или я чего-то не понимаю?

Да ты прав в этом)
