### ISSUE TITLE
Подсветка ссылок в футере и при наведении на статьи НЕ оранжевая для темы "день"

### ISSUE THREAD

**Issue by Lyub0vN** [razrabs-media/journal#385]
ФР: при наведении на **текст в футере** подсветка фиолетовая (как в режиме "ночь") 
аналогично **для подсказок** (при наведении на статьи)
![Image](https://user-images.githubusercontent.com/108517908/183840201-701a43e7-22c0-4cc3-83e4-7920763bf1c9.png)
![Image](https://user-images.githubusercontent.com/108517908/183843111-35292156-73d4-4f5b-b8bd-82c8ca4d8f32.png)

ОР: https://www.figma.com/file/NO0RmwhfZnsOjW1cexIVEW/%F0%9F%94%B8-rzrbs?node-id=4370%3A9759 (вся подсветка оранжевая в режиме "день")

**Comment by gkopylovdev** [comment]
@batyshkaLenin Бахни на меня, вечерком сделаю

**Comment by Lyub0vN** [comment]
Не сразу обратила внимание
При наведении на хедер аналогично 

![Image](https://user-images.githubusercontent.com/108517908/183854382-d8626571-abee-4411-8291-a9a768cec9c7.png)

Норм будет все в общей задаче править?
