### ISSUE TITLE
Не отцентрирована главная страница на широком девайсе (iPhone X, 375 x 812)

### ISSUE THREAD

**Issue by Lyub0vN** [razrabs-media/journal#386]
ФР: скрин с **dev**.razrabs.ru (**на проде все ОК**)
![Image](https://user-images.githubusercontent.com/108517908/183850385-606088a8-d466-4fe7-b7ce-ca3d07a6af07.png)

ОР: скрин с прода razrabs.ru
![Image](https://user-images.githubusercontent.com/108517908/183850517-de90a5e1-d0dc-417b-a278-d9065ba9430f.png)

**Comment by batyshkaLenin** [comment]
Воспроизвелась #372

**Comment by 6y6b07** [comment]
Аналогично  на Андройде
