### ISSUE TITLE
Стили применяются в разном порядке при локальной разработке и в проде.

### ISSUE THREAD

**Issue by wadzari** [razrabs-media/journal#393]
**Описание ошибки**
Стили в dev и prod применяются в разном порядке.

**Как воспроизвести**
Шаги для воспроизведения проблемы:
1. Перейти в акканут пользователя
2. В devtools посмотреть на margin в последних строках
3. В случае прода, будет применятся margin-bottom 
4. Локально он будет перебиваться.

**Ожидаемое поведение**
Порядок применения стилей одинаковый

**Скриншоты**
<details>
  <summary>prod</summary>

![Screenshot from 2022-08-11 00-28-40](https://user-images.githubusercontent.com/34591001/184025718-28416c0f-bc3a-4a7e-8fdf-859194170675.png)

</details>

<details>
  <summary>dev</summary>

![Screenshot from 2022-08-11 00-30-01](https://user-images.githubusercontent.com/34591001/184025879-ba7ef92e-0e39-4abb-b940-b1e63611f99d.png)

</details>

**Устройство:**
 - OS: Ubuntu 20.04
 - Браузер: Google Chrome
 - Версия браузера: Version 104.0.5112.79 (Official Build) (64-bit)

**Comment by batyshkaLenin** [comment]
`Стили в dev и prod применяются в разном порядке.`  
Потому что версия которая щас на проде и версия которая актуальная в мастере это две разные версии? Ну т.е. буквально разных фиксов принесли, как-то переработали вёрстку и стили. Было бы странно, если бы отличий не было. Или я что-то не так понимаю?

**Comment by wadzari** [comment]
Да, переключился в релизный [коммит](https://github.com/razrabs-media/journal/releases/tag/v.1.0.5). Там с порядком применения стилей все ок. Видимо что-то случилось :thinking:
