### ISSUE TITLE
При двойном нажатие на кнопку для отправки комментария, комментарий дублируется.

### ISSUE THREAD

**Issue by 6y6b07** [razrabs-media/journal#394]
После первого клика реакт не сразу ставит лоудинг, а ждёт батча и в этот батч можно успеть ткнуть ещё раз.  Поле стирается только после ответа от сервера.

**Comment by gkopylovdev** [comment]
Взял в работу, часто встречаются дублирующиеся записи
@batyshkaLenin Назначь меня плз
