### ISSUE TITLE
При светлой теме, цвет текста в кнопке аккаунта не соответствует макету

### ISSUE THREAD

**Issue by 6y6b07** [razrabs-media/journal#414]
Сейчас 

![Image](https://user-images.githubusercontent.com/101573341/184428237-8ef1e1e1-d22c-429b-a577-3e4ecc8d50a8.jpg)

**Comment by 6y6b07** [comment]
Ожидаемо 

![Image](https://user-images.githubusercontent.com/101573341/184428271-fa98f5c7-124d-4a63-8441-92db7fc0e5cd.jpg)

**Comment by gkopylovdev** [comment]
Взял
