### ISSUE TITLE
В кнопке аккаунта у авторизованного пользователя, ожидаемо отображение двух символов, даже если у пользователя в Гите указанно только имя.

### ISSUE THREAD

**Issue by 6y6b07** [razrabs-media/journal#415]
Сейчас 

![Image](https://user-images.githubusercontent.com/101573341/184430758-41ce2a5a-0023-462d-8392-1e02b151c796.jpg)

**Comment by gkopylovdev** [comment]
Не совсем понятно, по какой логике тогда составлять текст в этой кнопке? Первые два символа имени? Кмк достаточно странно, мб стоит оставить один символ, если нет фамилии

**Comment by 6y6b07** [comment]
Один символ не красиво )

**Comment by gkopylovdev** [comment]
Продуктовый вопрос надо/не надо
@philippranzhin

**Comment by philippranzhin** [comment]
Брать два из имени

**Comment by gkopylovdev** [comment]
Взял
