### ISSUE TITLE
Разработать цветовую тему для блоков кода

### ISSUE THREAD

**Issue by raantoniv** [razrabs-media/journal#418]
Разработать цветовую тему для блоков кода

_Originally posted by @raantoniv in https://github.com/razrabs-media/journal/issues/417#issuecomment-1214430336_

**Comment by GNMKR** [comment]
заасайните плиз

**Comment by GNMKR** [comment]
@raantoniv 
Я же правильно понимаю, что под цветовой темой имеется ввиду сбор всех цветов из [codeTheme](https://github.com/razrabs-media/journal/blob/7683ab7d8e189c30a09b14b6ae640bf8ee3959cf/src/shared/ui/markdown-renderer/theme.ts) и упорядочивание их в условный `enum Colors {...}`?
