### ISSUE TITLE
Привести дизайн в соответствии с макетами

### ISSUE THREAD

**Issue by nahuka3** [razrabs-media/journal#425]
https://github.com/razrabs-media/journal/issues/181
https://github.com/razrabs-media/journal/issues/179
https://github.com/razrabs-media/journal-backoffice-web/issues/46
https://github.com/razrabs-media/journal/issues/257
https://github.com/razrabs-media/journal/issues/264
https://github.com/razrabs-media/journal/issues/401
https://github.com/razrabs-media/journal/issues/402
https://github.com/razrabs-media/journal/issues/411

**Comment by batyshkaLenin** [comment]
Эту задачу нереально решать, потому что она не содержит в себе никакой конкретики. У нас есть майлстоун, где есть конкретные задачи по правкам для приведения к макету: [https://github.com/razrabs-media/journal/milestone/6](https://github.com/razrabs-media/journal/milestone/6)

**Comment by batyshkaLenin** [comment]
Все задачи перенёс в milestone
