### ISSUE TITLE
Не работает https://api.dev.razrabs.ru/gql

### ISSUE THREAD

**Issue by GNMKR** [razrabs-media/journal#433]
**Описание ошибки**
При обращении к https://api.dev.razrabs.ru (NEXT_PUBLIC_API_GATEWAY) падает ошибка 404

<img width="510" alt="Screenshot 2022-08-17 at 23 02 39" src="https://user-images.githubusercontent.com/110541469/185232844-e6eeaccf-a2a7-4dad-a881-1aff8c906793.png">
<img width="675" alt="Screenshot 2022-08-17 at 23 03 46" src="https://user-images.githubusercontent.com/110541469/185232853-0228ddee-09d2-4e7e-8c4e-35a78694f42c.png">

**Comment by philippranzhin** [comment]
У нас девстенд на какое-то время сдох, скоро поднимем
