### ISSUE TITLE
Кнопка "Поделиться" не работает

### ISSUE THREAD

**Issue by leffsu** [razrabs-media/journal#434]
**Описание ошибки**
При нажатии на кнопку "Поделиться" ничего не происходит. В буфер обмена ссылка не кладется. 

**Как воспроизвести**
Шаги для воспроизведения проблемы:
1. Перейти на страницу публикации.
2. Сжать страницу по ширине.
3. Нажать на кнопку "Поделиться".
4. Ничего не происходит. 

**Ожидаемое поведение**
Либо в буфер ссылка кладется, либо показывается диалог для показа.

**Скриншоты**
<img width="632" alt="image" src="https://user-images.githubusercontent.com/30364628/185464414-e6d948ac-8bac-41bd-a649-c4ee425aae07.png">

**Устройство:**
Можно указать, на каком устройстве была обнаружена проблема. В случае с телефоном можно указать модель.
 - MacOS
 - Chrome
 - 104.0.5112.79 (Official Build) (arm64)

**Comment by gkopylovdev** [comment]
Взял
