### ISSUE TITLE
Мобильная версия. Контент не адаптируется под размер экрана, в случаи наличия ссылок в материале.

### ISSUE THREAD

**Issue by 6y6b07** [razrabs-media/journal#501]
Шаги

1. Загрузить статью, в контенте которой имеются сслыки на какие либо сайты. 
2. Открыть статью в мобильной версии.
3. Обратить внимание на адаптацию контента.

**Comment by 6y6b07** [comment]
![Image](https://user-images.githubusercontent.com/101573341/191543068-836f9eb8-ce30-408a-8408-9c00edca7249.png)

**Comment by 6y6b07** [comment]
https://dev.razrabs.ru/post/bc8110d0-b7f4-49f2-9531-ab1819364b37

**Comment by gelugu** [comment]
@6y6b07 привет, сделал ПР, если есть возможность посмотри плиз.

Скрин:
<img width="705" alt="image" src="https://user-images.githubusercontent.com/19702031/192166004-c4563ad1-4e1c-4a28-a696-0f2ad5406523.png">

Проблема была не только с мобильной вёрсткой, на десктопе вёрстка так же ломалась (ссылка уходила за пределы экрана).

**Comment by gelugu** [comment]
[@nahuka3](https://github.com/nahuka3), [@batyshkaLenin](https://github.com/batyshkaLenin) нужен ассайгн

[@evist0](https://github.com/evist0), [default-razrab](https://github.com/default-razrab), [@raantoniv](https://github.com/raantoniv) нужно ревью
