### ISSUE TITLE
BUG В мобильной версии, в материале, примеры кода не адаптируются под размер экрана

### ISSUE THREAD

**Issue by philippranzhin** [razrabs-media/journal#66]
![Image](https://user-images.githubusercontent.com/101573341/169837175-a24925c3-fec6-412e-a590-4c0a36990b0e.png)

![Image](https://user-images.githubusercontent.com/101573341/169837452-9ffc48d6-95ce-471b-a1be-eda2fb335705.png)

**Comment by evist0** [comment]
можно вправо проскроллить же и посмотреть))

как должна выглядеть адаптивность?
