### ISSUE TITLE
Журнал, после обновления материала, обновление в журнале происходит с задержкой

### ISSUE THREAD

**Issue by philippranzhin** [razrabs-media/journal#72]

**Comment by philippranzhin** [comment]
@raantoniv что скажешь?

**Comment by 6y6b07** [comment]
![Image](https://user-images.githubusercontent.com/101573341/172828089-44b60b8d-b82f-4728-9484-6172bee860df.png)



![Image](https://user-images.githubusercontent.com/101573341/172828133-6f60fa0f-c18f-4ec0-94f2-7d152b4519da.png)
